name: Deploy To Github page
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: 'Run flutter pub get'
        run: |
          flutter pub add caf_flutter_ui --git-url=https://${{ secrets.CAF_UI_SECRETS }}@github.com/picklesventuresorg/caf_flutter_ui.git --git-ref=develop
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
      - name: 'Build flutter web'
        run: flutter build web --release
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
