name: Deploy To Github page
on:
  push:
    branches:
      - task/soethan_action_deploy_test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Configure git for private package
        run: git config --global url."git@github.com:".insteadOf "https://github.com/"

      - name: 'Run flutter pub get'
        run: flutter pub get
      - name: 'Run flutter build'
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: 'Build flutter web'
        run: flutter build web --release
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
